### ISSUE TITLE
Zoom Icon Scaling

### ISSUE THREAD

**Issue by keawade** [Moser2010/d-dMap#7]
Icons aren't scaling properly when at maximum zoom out.

![zoomissue](https://cloud.githubusercontent.com/assets/7308850/26497992/0bfd3576-41f3-11e7-8026-9fd80d0d56fa.PNG)

**Comment by Moser2010** [comment]
Thanks for the input. I know that this was something I looked a lot at and I have heard this from everyone that has played with the site. The problem is that I can't find a solution anywhere because this is an issue with leaflet.js itself not with something that I am doing which means my options are to mess with their code, eeekkk, or for me to change to a different library.
